name: Deploy via SSH to Windows Server

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/cloudflared

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH config
        run: |
          mkdir -p ~/.ssh
          echo "Host ssh-windows-server
            HostName ssh-windows-server.aiotlab.edu.vn
            User Administrator
            Port 22
          " > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ssh-windows-server "echo Hello from GitHub Actions && whoami && dir C:\\Users\\Administrator"